// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe40lV9bL5UclWo-e2Socn633ZpYTL0gw',
    appId: '1:1095305802843:web:36473956e6371627f43b7e',
    messagingSenderId: '1095305802843',
    projectId: 'meal-planner-app-23550',
    authDomain: 'meal-planner-app-23550.firebaseapp.com',
    storageBucket: 'meal-planner-app-23550.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPtCnJ7L0SEqFRybrrAvcEwvls36SPPE',
    appId: '1:1095305802843:android:06286a0a862749f9f43b7e',
    messagingSenderId: '1095305802843',
    projectId: 'meal-planner-app-23550',
    storageBucket: 'meal-planner-app-23550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghjcnilqjtCzkl2W5yCZJc4gC6LNFW6A',
    appId: '1:1095305802843:ios:e606e094081bf318f43b7e',
    messagingSenderId: '1095305802843',
    projectId: 'meal-planner-app-23550',
    storageBucket: 'meal-planner-app-23550.appspot.com',
    androidClientId: '1095305802843-cuqbjovi6l6rcgbgeajumvbbbmrsjblv.apps.googleusercontent.com',
    iosClientId: '1095305802843-12bfo2qoef12oaedd395hcg8ecvnm2v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghjcnilqjtCzkl2W5yCZJc4gC6LNFW6A',
    appId: '1:1095305802843:ios:e606e094081bf318f43b7e',
    messagingSenderId: '1095305802843',
    projectId: 'meal-planner-app-23550',
    storageBucket: 'meal-planner-app-23550.appspot.com',
    androidClientId: '1095305802843-cuqbjovi6l6rcgbgeajumvbbbmrsjblv.apps.googleusercontent.com',
    iosClientId: '1095305802843-12bfo2qoef12oaedd395hcg8ecvnm2v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanner',
  );
}
